export class MapStates {
  statelist = {
    Massachusetts: 'Massachusetts',
    Minnesota: 'Minnesota',
    Montana: 'Montana',
    'North Dakota': 'North Dakota',
    Hawaii: 'Hawaii',
    Idaho: 'Idaho',
    Washington: 'Washington',
    Arizona: 'Arizona',
    California: 'California',
    Colorado: 'Colorado',
    Nevada: 'Nevada',
    'New Mexico': 'New Mexico',
    Oregon: 'Oregon',
    Utah: 'Utah',
    Wyoming: 'Wyoming',
    Arkansas: 'Arkansas',
    Iowa: 'Iowa',
    Kansas: 'Kansas',
    Missouri: 'Missouri',
    Nebraska: 'Nebraska',
    Oklahoma: 'Oklahoma',
    'South Dakota': 'South Dakota',
    Louisiana: 'Louisiana',
    Texas: 'Texas',
    Connecticut: 'Connecticut',
    'New Hampshire': 'New Hampshire',
    'Rhode Island': 'Rhode Island',
    Vermont: 'Vermont',
    Alabama: 'Alabama',
    Florida: 'Florida',
    Georgia: 'Georgia',
    Mississippi: 'Mississippi',
    'South Carolina': 'South Carolina',
    Illinois: 'Illinois',
    Indiana: 'Indiana',
    Kentucky: 'Kentucky',
    'North Carolina': 'North Carolina',
    Ohio: 'Ohio',
    Tennessee: 'Tennessee',
    Virginia: 'Virginia',
    Wisconsin: 'Wisconsin',
    'West Virginia': 'West Virginia',
    Delaware: 'Delaware',
    'District of Columbia': 'District of Columbia',
    Maryland: 'Maryland',
    'New Jersey': 'New Jersey',
    'New York': 'New York',
    Pennsylvania: 'Pennsylvania',
    Maine: 'Maine',
    Michigan: 'Michigan',
    Alaska: 'Alaska',
  };
}
